apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: jeffreyfreeland/flask-hello-world:v0.2
        ports:
        - containerPort: 5000
        env:
          - name: ENV_VAR_1
            value: "A Value From Kubernetes!"